config/routes.rb
Rails.application.routes.draw do
  root 'authors#index'

  resources :authors do
    resources :books
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
  
  validates :name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @author = Author.find(params[:author_id])
    @book = @author.books.create(book_params)
    redirect_to author_path(@author)
  end

  def destroy
    @author = Author.find(params[:author_id])
    @book = @author.books.find(params[:id])
    @book.destroy
    redirect_to author_path(@author), status: 303
  end

  private
    def book_params
      params.require(:book).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_with model: author do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name, class: 'input is-primary' %>
      <% author.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit class: 'button is-success' %>
    </div>
  <% end %>

app/views/authors/edit.html.erb
<h1> Edit Author</h1>

<%= render 'form', author: @author %>

app/views/authors/index.html.erb
<article class="panel is-primary">
  <p class="panel-heading">
    Authors <%= link_to 'Create new author', new_author_path, class: 'button is-info' %>
  </p>
  <p class="panel-tabs">
  
  </p>
  <% @authors.each do |author| %>
    <%= link_to author.name, author, class: 'panel-block' %>
  <% end %>
</article>

app/views/authors/new.html.erb
<article class="panel is-primary">
  <p class="panel-heading">
    Create new author
  </p>

  <%= render 'form', author: @author %>
  
</article>

app/views/authors/show.html.erb
<article class="panel is-warning">
  <p class="panel-heading">
    <%= @author.name %>
    <%= link_to 'Edit author', edit_author_path(@author), class: 'button is-info' %>
    <%= link_to "Destroy", 
      author_path(@author), 
      data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?",
      },
      class: 'button is-danger' 
    %>
  </p>
</article>
<article class="panel is-info">
  <p class="panel-heading">
    Add a book:
  </p>
  <p class="panel-block">
    <%= render 'books/form' %>
  </p>
</article>
<article class="panel is-link">
  <p class="panel-heading">
    List of books:
  </p>
  <p class="panel-block"
  <%= render @author.books %>
  </p>
</article>

app/views/books/_book.html.erb
<% if book.id %>
<p class="panel-block">
    <p> Title: <%= book.title %> </p> <br>
    <p> Description: <%= book.description %> </p>
    <p>
    <%= link_to "Delete book", [book.author, book], data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
        },
        class: 'button is-danger' %>
    </p>
</p>
<% end %>

app/views/books/_form.html.erb
<%= form_with model: [ @author, @author.books.build ] do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title, class: 'input is-primary' %>
    </p>
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description, class: 'textarea is-primary' %>
    </p>
    <p>
      <%= form.submit class: 'button is-success' %>
    </p>
  <% end %>

app/views/layouts/_footer.html.erb
<div class="stickyFooter">
<p> © Demo App by allesdmytro. 2022 </p>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <%= link_to 'Book store', root_path, class: 'logo' %>
  <div class="header-right">
    <%= link_to 'Home', root_path, class: 'active' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <%= render 'layouts/header' %>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>

  <%= render 'layouts/footer' %>
</html>